### PR TITLE
Update dyndns.sh

### LINKED ISSUE #13: services list throws error with sh
Hi,

Seems like the last commit has an issue with services list due to sh not supporting this functionality. Changing Line 1 from /bin/sh to bin/bash solves this issue.

https://github.com/tunix/digitalocean-dyndns/blob/688a19663eac7112cc84cf398d97475035f184bc/dyndns.sh#L6L9

### PR DESCRIPTION
**Pull request by otherguy**
Fixes #13

### CODE REVIEW

**Review by tunix — APPROVED** [review]
Sorry for the bug and thank you for your contribution!

**Comment by otherguy** [comment]
@tunix sure thing and thank you for making this in the first place! Would you mind publishing a new image to Dockerhub?

**Comment by tunix** [comment]
@otherguy - it's automatically built & pushed already by Docker Hub 👍🏻

**Comment by otherguy** [comment]
@tunix aha, thanks! My bad, I should have actually tested my PR. https://github.com/tunix/digitalocean-dyndns/pull/16 fixes the current issue and adds logging plus a third, faster, service.

**Pull request merged**
